### ISSUE TITLE
Change 'deplorables'

### ISSUE THREAD

**Issue by gryter** [steemit/irredeemables#1]
"Deplorables" is a racist term used to signify blue-collar (poor), mostly white people, by Hillary Clinton in the US election. 

 It is highly offensive and not appropriate for anything to do with STEEM, particularly as a label for users. 

Suggested Change: Bad Actors

**Comment by tcgirl** [comment]
A logical choice for a name would be irredeemable.

**Comment by goldibex** [comment]
`irredeemables` is a great name. Thanks to you for the suggestion, @tcgirl!

**Comment by gryter** [comment]
Why hasn't this been changed yet?
